# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-02OU2sMqB4w2PxO0rLEAuMh6IaZV6sp
"""

!pip install PyPDF2

!pip install reportlab

import PyPDF2
import re
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def ext_txt(p):
    try:
        with open(p, "rb") as f:
            r = PyPDF2.PdfReader(f)
            t = "\n".join(pg.extract_text() or "" for pg in r.pages)
        return t
    except Exception as e:
        print(f"Err: {e}")
        return ""

def cln_txt(t):
    t = re.sub(r'\d+', '', t)
    t = re.sub(r'[^\w\s]', '', t)
    return t

def cnt_w(t):
    return len(t.split())

def sv_txt(t, o):
    try:
        c = canvas.Canvas(o, pagesize=letter)
        w, h = letter
        c.setFont("Helvetica", 12)
        y = h - 40

        for l in t.split("\n"):
            c.drawString(40, y, l[:90])
            y -= 15
            if y < 40:
                c.showPage()
                c.setFont("Helvetica", 12)
                y = h - 40

        c.save()
        print(f"Saved: {o}")
    except Exception as e:
        print(f"Err: {e}")

def main():
    p = input("PDF path: ")
    t = ext_txt(p)
    if not t.strip():
        print("No text found.")
        return

    print(f"Org: {cnt_w(t)}")
    t = cln_txt(t)
    print(f"Upd: {cnt_w(t)}")

    sv_txt(t, "upd.pdf")

if __name__ == "__main__":
    main()

